### ISSUE TITLE
Use host X server istead of RDP proposal

### ISSUE THREAD

**Issue by juanvaccarezza** [DSD-DBS/capella-dockerimages#28]
Hi guys!
Thank you very much for this images are really useful. (I was getting mad about the downgrade dependencies of gtk) .

My little contribution is the following (how I use it):
I've created a docker-compose.yml like the following:

```
version: "3"
services:
  capella:
    image: capella/base:latest
    environment:
      - DISPLAY=${DISPLAY}
      - GTK_THEME=Adwaita
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./git:/git
      - ./extworkspace:/extworkspace
    network_mode: host
    entrypoint: ./capella/capella -data /extworkspace
```

Basically it sets the DISPLAY variable accordingly to execute GUIs application inside the docker and sets my git and an external workspace to use by default.

here some reference on GUI apps on docker.
https://gursimar27.medium.com/run-gui-applications-in-a-docker-container-ca625bad4638
